version: "3.3"
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: webcloud_db
    environment:
      MYSQL_DATABASE: "sql_web_cloud"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3308:3306"
#     volumes:
#       - my-db:/var/lib/mysql

# volumes:
#   my-db:
